# Exceptions (异常)

复习和学英文

1. robust (健壮的)
2. implement (执行计划/方案)
3. execute (执行代码)
4. illustrate (说明)
5. evaluated (评估)
6. coercing (强制)
7. handle exception (处理异常)


1. 异常类的子类也会引起错误

> For instance, if the < exception class > is AssertionError, then any instance of a class inheriting from
> AssertionError that is raised

2. 即使except写在错误发生的函数外，也能捕捉到异常

> A try statement will handle exceptions that occur within the body of a function that is applied (either directly or
> indirectly) within the < try suite >.

~~~python
def invert(x):
    result = 1 / x  # Raises a ZeroDivisionError if x is 0
    print('Never printed if x is 0')
    return result


def invert_safe(x):
    try:
        return invert(x)
    except ZeroDivisionError as e:
        return str(e)
~~~

## Exception Objects (异常对象)

我们可以自定义异常对象，只需继承Exception

下面例子中，我们模拟牛顿迭代法来求方程 2x^2+sqrt 2 = 0的根 ，并利用自定义的异常IterImproveError来记录最后一次的猜测值

我们知道不会有实根，根会无限接近0，所以它一定会报错

~~~python
from math import sqrt


class IterImproveError(Exception):
    def __init__(self, last_guess):
        self.last_guess = last_guess


def improve(update, done, guess=1, max_updates=1000):
    k = 0
    try:
        while not done(guess) and k < max_updates:
            guess = update(guess) 
            k = k + 1
        return guess
    except ValueError:
        raise IterImproveError(guess)


def newton_update(f, df):  # df是f的求导函数
    def update(x):
        return x - f(x) / df(x) # x为负数时会报错ValueError，因为f(x)中会对x开平方

    return update


def find_zero(f, df, guess=1):
    def done(x):
        return f(x) == 0

    try:
        return improve(newton_update(f, df), done, guess)
    except IterImproveError as e:
        print('error!')
        return e.last_guess


if __name__ == '__main__':
    result = find_zero(lambda x: 2 * x * x + sqrt(x), lambda x: 4 * x + 0.5 * x ** -.5)
    print(result)
~~~